### ISSUE TITLE
Sideloading issues

### ISSUE THREAD

**Issue by augustobob** [PoomSmart/YouQuality#11]
Sideloading partially works, I can touch the button but nothing shows up. Looks like the images is missing.

https://github.com/PoomSmart/YouQuality/assets/41238825/7f5cf148-2879-46ce-9f75-b97aeeccf7f7

**Comment by PoomSmart** [comment]
Ensure you include YouQuality.bundle in your sideloaded app.

**Comment by augustobob** [comment]
> Ensure you include YouQuality.bundle in your sideloaded app.

Is it possible to add this bundle with Esign?
