### ISSUE TITLE
“2K60 HDR” shows as “2K 6…R”

### ISSUE THREAD

**Issue by dora727** [PoomSmart/YouQuality#17]
I don’t know if this is screen size issue or sth.

Btw video link if you wanna test: https://youtu.be/YnY7qTo-Q1A?si=fx3SB3mOJgtjmtYj
![IMG_7014](https://github.com/PoomSmart/YouQuality/assets/109880918/ed60b313-20f5-4a54-9dda-cc07d5a843ec)
![IMG_7015](https://github.com/PoomSmart/YouQuality/assets/109880918/93763281-57b5-4774-9a52-b851aa0ba168)

**Comment by PoomSmart** [comment]
The issue has already been fixed in the latest version of YouQuality tweak.
