### ISSUE TITLE
[REQUEST] YouQuality for 48fps and 50fps

### ISSUE THREAD

**Issue by dora727** [PoomSmart/YouQuality#9]
I realized when I watch a video with 48fps or 50fps, the YouQuality overlay will disappear.
(60 is fine)

So I wonder if YouQuality has support for those video.

![IMG_9750](https://github.com/PoomSmart/YouQuality/assets/109880918/7b7837da-8d3a-4187-bc1b-5871bc13c534)
![IMG_9752](https://github.com/PoomSmart/YouQuality/assets/109880918/501baa0d-8bdd-42c5-886b-438308cc2b91)

**Comment by PoomSmart** [comment]
Fixed
